<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
		<string>i</string>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>M68k-Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.double.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.quoted.single.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;[^
]*
</string>
			<key>name</key>
			<string>comment.line.semicolon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|[ 	])\*(?![+-])[^
]*
</string>
			<key>name</key>
			<string>comment.line.asterisk</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.symbol.m68k</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^([a-zA-Z0-9_][a-zA-Z0-9_\.]*)(?=([ 	]*=|[ 	]+equ[ 	]+))</string>
			<key>name</key>
			<string>meta.equate.m68k</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.macro.m68k</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.other.macro.m68k</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(^([a-zA-Z0-9_\.]+)(:[ 	]*|[ 	]+)macro|^[ 	]+macro[ 	]+([a-zA-Z0-9_\.]+))[ 	]*$</string>
			<key>name</key>
			<string>meta.macro.m68k</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.section.name.m68k</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\bsection[ 	]+("[^"]+"|'[^']+'|[^,]+)</string>
			<key>name</key>
			<string>meta.section.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[a-zA-Z_]([a-zA-Z0-9_]*|[a-zA-Z0-9_\.%\$]*[a-zA-Z0-9_])(?=[ 	:])</string>
			<key>name</key>
			<string>meta.label.global.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])\$[0-9A-Fa-f]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])@[0-7]+\b</string>
			<key>name</key>
			<string>constant.numeric.octal.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])%[01]+\b</string>
			<key>name</key>
			<string>constant.numeric.binary.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;![a-zA-Z])[+-]?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.decimal.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b([ad][0-7]|SP|PC|vbr|fp[0-7])\b</string>
			<key>name</key>
			<string>variable.language.register.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(abcd|bchg|bclr|bset|chk|divs|divu|exg|jmp|jsr|lea|link|movec|moveq|muls|mulu|nbcd|nop|pea|reset|rte|rtr|rts|sbcd|stop|swap|tas|trap|trapv|unlk)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(add|addi|addq|addx|and|andi|asl|asr|clr|cmp|cmpi|cmpm|eor|eori|lsl|lsr|move|neg|negx|not|or|ori|rol|ror|roxl|roxr|sub|subi|subq|subx|tst)(\.[bwl])?\b</string>
			<key>name</key>
			<string>keyword.other.opcode.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(adda|cmpa|ext|movea|movem|movep|suba)(\.[wl])?\b</string>
			<key>name</key>
			<string>keyword.other.opcode.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bbtst(\.[bl])?\b</string>
			<key>name</key>
			<string>keyword.other.opcode.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(bsr|bra|b(cs|lo|ls|eq|ne|hi|cc|hs|lt|le|eq|ne|gt|ge|pl|mi|vc|vs))(\.[bsw])?\b</string>
			<key>name</key>
			<string>keyword.other.opcode.branch.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bdb(cs|lo|ls|eq|ne|hi|cc|hs|lt|le|eq|ne|gt|ge|pl|mi|vc|vs|f|t|ra)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.dbcc.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bs(cs|lo|ls|eq|ne|hi|cc|hs|lt|le|eq|ne|gt|ge|pl|mi|vc|vs|f|t)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.scc.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\btrap(cs|lo|ls|eq|ne|hi|cc|hs|lt|le|eq|ne|gt|ge|pl|mi|vc|vs|f|t)(\.[wl])?\b</string>
			<key>name</key>
			<string>keyword.other.opcode.trapcc.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\billegal\b</string>
			<key>name</key>
			<string>invalid.illegal.opcode.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bf(abs|acos|add|asin|atan|atanh|cmp|cos|cosh|dadd|ddiv|dmul|div|dsub|etox|etoxm1|getexp|getman|int|intrz|log10|log2|logn|lognp1|mod|move|movecr|movem|mul|neg|nop|rem|restore|sadd|save|scale|sdiv|sgldiv|sglmul|sin|sincos|sinh|smul|sqrt|ssub|sub|tan|tanh|tentox|tst|twotox)(\.[bwlsdx])?\b</string>
			<key>name</key>
			<string>keyword.other.opcode.fpu.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bfb(cs|lo|ls|eq|ne|hi|cc|hs|lt|le|eq|ne|gt|ge|pl|mi|vc|vs)(\.[bsw])?\b</string>
			<key>name</key>
			<string>keyword.other.opcode.fpu.branch.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bfdb(cs|lo|ls|eq|ne|hi|cc|hs|lt|le|eq|ne|gt|ge|pl|mi|vc|vs|f|t|ra)(\.[bsw])?\b</string>
			<key>name</key>
			<string>keyword.other.opcode.fpu.dbcc.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bfs(cs|lo|ls|eq|ne|hi|cc|hs|lt|le|eq|ne|gt|ge|pl|mi|vc|vs|f|t)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.fpu.scc.m68k</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\bftrap(cs|lo|ls|eq|ne|hi|cc|hs|lt|le|eq|ne|gt|ge|pl|mi|vc|vs|f|t)\b</string>
			<key>name</key>
			<string>keyword.other.opcode.fpu.ftrapcc.m68k</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.m68k</string>
	<key>uuid</key>
	<string>fe8dd09c-dc33-41eb-83d4-4cc6ed720ad2</string>
</dict>
</plist>
